spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/onlinemusic?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mybatis/**Mapper.xml
debug: true
logging:
  level:
    root: info
    org.chengrong.onlinemusic.mapper: debug
    org.chengrong: debug

music:
  local:
    path: D:/music1/